### ISSUE TITLE
Test Data

### ISSUE THREAD

**Issue by yashasaxena** [yashasaxena/bme590hrm#13]
We should make some good and glitchy data for our unit tests at some point for data validation tests. 

Glitchy Data Properties:
- Missing headers
- third column in one row
- faulty data (strings, weird characters, abnormal voltages--broken ECG machine?)

**Comment by ss842** [comment]
file names, currently in Sonali branch:

GoodData_UnitTest.csv
FaultyData_UnitTest.csv
