### ISSUE TITLE
Avg vs Instantaneous Clarification

### ISSUE THREAD

**Issue by yashasaxena** [yashasaxena/bme590hrm#14]
I'm a little new to ECG data, so we are a little conflicted on how to define average vs instantaneous:

Is instantaneous heart rate a value calculated from a single peak-to-peak interval or is it a fixed time interval of 10 s...so you extrapolate the bpm by multiplying by 6?

Is average the total beats divided by the entire time interval?

We just want to have a clear idea, so we can define our unit test inputs accordingly.

Thanks!

**Comment by mlp6** [comment]
You've identified one of the under-specified functional requirements... there is no "correct" way to do this, but it would be best to identify the ways that you could do it, and see if you can write your function(s) to accommodate testing different schemes to see which are more robust, etc.  We'll be introducing some "user stories" in lecture tomorrow to provide some additional insight.
