### ISSUE TITLE
Average HR: Calculating Min Diff b/t time values and the averaging time

### ISSUE THREAD

**Issue by jhoballah** [yashasaxena/bme590hrm#32]
I'm having an issue when trying to find the index at which the difference between the seconds values in our time array and the inputted averaging time. I've set up the index position as follows, but I keep getting an error saying "E       TypeError: only integer scalar arrays can be converted to a scalar index"

index_pos = np.argwhere(min(abs(time_array - averaging_time_sec)))

Is there a better way to go about finding that index position?

**Comment by ad12** [comment]
Are you trying to find the index where the the time_array is close to the averaging_time_sec?

**Comment by jhoballah** [comment]
Yup!

**Comment by ad12** [comment]
If XXX was your numpy array, the syntax should be 

index_pos = np.argwhere(XXX == min(abs(time_array - averaging_time_sec)))

Check this link out: https://docs.scipy.org/doc/numpy-1.13.0/reference/generated/numpy.argwhere.html

**Comment by jhoballah** [comment]
Gotcha. What would the XXX numpy array contain in this situation? I have a method that finds the correct index using a for loop (in case I can't figure this out in time), but I was trying to find a more elegant solution.
