### ISSUE TITLE
Sphinx Set up Error

### ISSUE THREAD

**Issue by yashasaxena** [yashasaxena/bme590hrm#44]
Screen shot of errors generated (looks like same error) when trying to set up our index.html after sphinx set up:
<img width="876" alt="screen shot 2017-10-03 at 4 03 16 pm" src="https://user-images.githubusercontent.com/8584289/31146378-770a5f84-a854-11e7-9b20-5691d6b8266d.png">

**Comment by yashasaxena** [comment]
new issue

<img width="966" alt="screen shot 2017-10-03 at 7 59 48 pm" src="https://user-images.githubusercontent.com/8584289/31154499-7dcc566c-a875-11e7-8dc6-7f94854766dd.png">

**Comment by mlp6** [comment]
Hmmmm...

**Comment by suyashkumar** [comment]
@yashasaxena I think the issue here is that sphinx doesn't see an extension that it needs. In the `docs/conf.py` you should see an `extensions = []` line. Based on @mlp6's config [here](https://github.com/mlp6/fem/blob/master/docs/conf.py), you should probably change that line to:

```
extensions = [
    'sphinx.ext.autodoc',
]
```

Let me know if that helps and works out

**Comment by mlp6** [comment]
I agree w/ what Suyash said... that extension should be enabled when you run `sphinx-quickstart` and you choose `Y` to the `autodoc` functionality.  You can manually add that using the option @suyashkumar mentions above.

**Comment by yashasaxena** [comment]
yup, so we did that in class. and i managed to resolve "document isn't included in the toc tree" by listing files we don't need documented in the exclude_patterns statement in conf.py
now there are no errors being thrown but also modules are empty on index.html, so now i'm thinking we pooched the actual documentation

I also don't see it in the table of contents, i have to search for it in the search bar and this is what it ends up looking like:
<img width="758" alt="screen shot 2017-10-04 at 9 30 33 am" src="https://user-images.githubusercontent.com/8584289/31178356-cb8ba530-a8e6-11e7-93e7-1ca9aed5f304.png">
