### ISSUE TITLE
Subclass Vitals - Condensing 

### ISSUE THREAD

**Issue by ss842** [yashasaxena/bme590hrm#48]
condense code in subclass vitals

-write code for avgHR - use only 1 method as opposed to our current 2
-make 2 attributes (already have), both based on this one method, and use a smaller averaging window for this

**Comment by ss842** [comment]
Hi @jhoballah I thikn we can close this issue. i just checked out your code and it looks like you did the new process of finding avg HR then using a smaller index for determining inst HR from that. feel free to close at your discretion

**Comment by jhoballah** [comment]
Sure thing. I'm still not sure if I did it as cleanly as possible so I'm gonna ask tomorrow and then close once I'm more sure about it, if that's ok?

**Comment by ss842** [comment]
ya sounds good
