### ISSUE TITLE
Sphinx Struggles - Can you guys try on your terminals?

### ISSUE THREAD

**Issue by yashasaxena** [yashasaxena/bme590hrm#50]
Hi Dr. Palmeri,

I'm having no luck with my sphinx issues =(. Cleaned up all our doc strings in HR_allfuncs.py and still no dice. Would you mind running it on your end and seeing if you get different results or if I missed something major? 

Sonali, Jawad - when you get the chance can you run it in the virtual environment. The branch is now up to date. 

The only main error I'm seeing in the terminal is that the py files I do not list in index.rst are not listed in the toc string, which I would think is fine cus I don't want them to be documented. 

If we continue to have problems, should we consider starting from scratch? 
Would this be accomplished by deleting the docs folder and rerunning sphinx command? 

Halp plz.

**Comment by mlp6** [comment]
Do you have a branch that has your attempts at creating `docs/`?

**Comment by yashasaxena** [comment]
Yup we stopped using the master branch after tagging it as a release.

All work related to sphinx was done in branch called "HW02B"

**Comment by ss842** [comment]
![image](https://user-images.githubusercontent.com/31519918/31318634-9d01013e-ac23-11e7-8367-d1acd39a5acf.png)

it's working!!  @yashasaxena

**Comment by ss842** [comment]
so now we have to fix the actual commentary 
- "..function"
-add the parameters/return type etc

but i'm gonna go to the beach and do that later (s/o to clob [caleb] for helping me)

**Comment by ss842** [comment]
make sure you look in the correct folder when opening the html, you were not deep enough into the folder i think (see below)
![image](https://user-images.githubusercontent.com/31519918/31318736-b76ccbce-ac24-11e7-85ba-1fde1549c482.png)

I think you were opening in build, that's where the "empty" index is

**Comment by yashasaxena** [comment]
OH MY GOD YES! THANK YOU SONALI SHAH!

**Comment by yashasaxena** [comment]
Please enjoy the beach Caleb and Sonali, you all are my saviours, time for me to cry tears of joy:
<img width="949" alt="screen shot 2017-10-08 at 1 36 06 pm" src="https://user-images.githubusercontent.com/8584289/31319233-b091f23a-ac2d-11e7-9d15-430887938d44.png">
