### ISSUE TITLE
PEP8 failures

### ISSUE THREAD

**Issue by mlp6** [yashasaxena/bme590hrm#53]
check out the output of `py.test -v --pep8`

**Comment by ss842** [comment]
![image](https://user-images.githubusercontent.com/31519918/31515583-a48991e4-af63-11e7-896f-97d527344387.png)

@mlp6 pep8 is in our environment file, and i just ran the unit tests so i know it's active. any thoughts on this feedback on git

**Comment by mlp6** [comment]
Are you working in your active python virtual environment?  It doesn't appear that you are from your screenshot, which would mean that package isn't available.

**Comment by ss842** [comment]
you're right :(

**Comment by ss842** [comment]
![image](https://user-images.githubusercontent.com/31519918/31516712-7ce8ed20-af67-11e7-8168-831e47723aa2.png)

**Comment by mlp6** [comment]
Make sure that you local conda virtual environment actually has `scipy` installed.  I see that it is part of your `environment.yml` file now, but if an earlier version was missing that package and your local environment was created from that earlier config file, then you might be missing it.  #sonalihasprogrammingskilz

**Comment by ss842** [comment]
ok i'll look into it. thanks! the encouragement is helpful lol

**Comment by ss842** [comment]
HRM_classfile.py is now pep8 approved 
HR_allfuncs.py - we don't care about anymore
test_data_processing.py - some problems 
look at jawad's test functions

**Comment by ss842** [comment]
hi @mlp6, we've been working on this issue as we continue our work.  we've made progress but there are some errors in the new version tag (focused more on other parts of assignment). closing this issue for now as we are submitting as is
