### ISSUE TITLE
unit test warnings

### ISSUE THREAD

**Issue by mlp6** [yashasaxena/bme590hrm#54]
check out the `py.test` output

**Comment by jhoballah** [comment]
Hi Dr. Palmeri, I just ran py.test to double check and I'm getting all unit tests passing on my end, do you happen to know which were failing for you?

**Comment by mlp6** [comment]
I get the following warnings (not errors, but these could be leading to false passing status):
```
test_avghr.py:166
  assertion is always true, perhaps remove parentheses?

test_avghr.py:158
  assertion is always true, perhaps remove parentheses?

test_avghr.py:132
  assertion is always true, perhaps remove parentheses?

test_avghr.py:124
  assertion is always true, perhaps remove parentheses?

test_avghr.py:98
  assertion is always true, perhaps remove parentheses?

test_avghr.py:90
  assertion is always true, perhaps remove parentheses?

test_avghr.py:82
  assertion is always true, perhaps remove parentheses?
```

**Comment by mlp6** [comment]
"fail" was not the correct word to use in the issue title!

**Comment by jhoballah** [comment]
Ah, no worries, thanks! I figured out why it was acting up, thanks so much!

**Comment by ss842** [comment]
@jhoballah  i'm currently having this issue on some of my unit tests... what did you do on yours?

**Comment by ss842** [comment]
@jhoballah

**Comment by jhoballah** [comment]
I thought we fixed them? Which ones are acting up for you?

**Comment by ss842** [comment]
it's on mine/yasha's unit tests. we have the same assertion is always true perhaps remove parentheses problem

**Comment by jhoballah** [comment]
Could you tell me an example test and I’ll look? 
I think you’ll just need to assert that your attribute == what value you’re looking for

**Comment by ss842** [comment]
yeah, i'm trying to fix the scipy situation from issue #53 so that i can show you. yasha is trying to run the py.test -v now

**Comment by ss842** [comment]
nevermind, it's not throwing errors anymore! @jhoballah

**Comment by jhoballah** [comment]
Nice! What was the issue ultimately?

**Comment by ss842** [comment]
idk, it's been a few days and we've done a lot and hadn't tried the py test in a while because my environment is mad so yasha just tried it today. i think my path for the environment is messed up since the first assignment, arjun couldn't figure it out either
