### ISSUE TITLE
Question about Data Validation

### ISSUE THREAD

**Issue by ss842** [yashasaxena/bme590hrm#6]
Will our code need to identify time vs voltage columns, or can we assume time is column 1? 

Follow up - Will python automatically be able to work with integers and convert to float, or should we address that in our code (convert all integers to floats ourselves) / unit test (address the same way we plan to raise an error if code encounters string type)? 
 
*apologies in advance for my bad coding syntax...

**Comment by mlp6** [comment]
The specification is that time is in column 1, so you can go with that.

Are you asking the int/float question in the context of performing mathematical operations?  If so, then I would recommend testing that out in an interactive session.

**Comment by ss842** [comment]
Thanks @mlp6 !!
