### ISSUE TITLE
Update unit tests to account for using a Class-based system

### ISSUE THREAD

**Issue by jhoballah** [yashasaxena/bme590hrm#63]
Hey squad, we need to remember to update our unit tests accordingly. I've got my ones working on diagnosis currently, so check the latest commit (SHA listed below) to see the syntax <3

f2bea958c704830686d2359f35e99fa38b3c308d

**Comment by ss842** [comment]
![image](https://user-images.githubusercontent.com/31519918/31474356-3320c4aa-aec8-11e7-9562-62749c3dae54.png)

HAHHHHHH

**Comment by ss842** [comment]
ready to ******* merge w vitals/diagnosis branch

![image](https://user-images.githubusercontent.com/31519918/31474614-d51cee18-aec9-11e7-8312-ac6cd4ab9e1a.png)
