### ISSUE TITLE
Merging WIP branch delay

### ISSUE THREAD

**Issue by yashasaxena** [yashasaxena/bme590hrm#69]
Hi Dr. Palmeri,

All of us are a little out of commission for the next few hours:
- Sonali has an MEng event
- Jawad's computer is crashing
- I am at work until 8 pm

We promise we will have our WIP branch ready for you around 8 pm, I wanted to bring this up to you in class but we didn't get the chance. Please look at our classmates branches before ours. I will close this issue and create the pull request when we are ready to merge.

Thanks,
Yasha

**Comment by jhoballah** [comment]
Yeah, to clarify, all my files are gone from my computer and I’m currently debugging the restore process

**Comment by mlp6** [comment]
@jhoballah oh my... let me guess, a Mac, right?  ;)

**Comment by mlp6** [comment]
I will review your project last tonight to give you as much time as possible...

**Comment by jhoballah** [comment]
@mlp6 You guessed correctly haha. All my files are gone and I’m mildly concerned because this backup restore process keeps bugging out, it’s been two hours with Apple support so far 😭

**Comment by mlp6** [comment]
Well, at least you know you can find comfort in the saturated fat and sodium content of a nice Big Mac.

**Comment by mlp6** [comment]
It actually isn't as bad as I thought it might be: http://www.calorieking.com/foods/calories-in-sandwiches-burgers-big-mac-burger_f-ZmlkPTEwMTAyOA.html

**Comment by yashasaxena** [comment]
finally
