### ISSUE TITLE
The Final Checklist

### ISSUE THREAD

**Issue by yashasaxena** [yashasaxena/bme590hrm#74]
**1) Edit Patient class file**
2) Put subclasses into separate files
3) Fix unit tests according to class changes
4) Make glob file that runs through test data files
5) Test out HR data 
6) Modify peak detect function if need be 
7) Adjust architecture for opening and parsing file, slash passing data.
8) Ensure all errors are caught in Patient class
**9) Test everything, please Travis gods**

**Comment by ss842** [comment]
1) Edit Patient class file --> done
2) Put subclasses into separate files --> done
3) Fix unit tests according to class changes --> done
4) Make glob file that runs through test data files --> ???
5) Test out HR data --> done-ish
6) Modify peak detect function if need be --? done-ish
7) Adjust architecture for opening and parsing file, slash passing data. --> done
8) Ensure all errors are caught in Patient class --> ???
9) Test everything, please Travis gods --> ClassComposition is happy so far with Data and Processing class

**Comment by jhoballah** [comment]
I'll make sure all errors are caught in the Patient class. They're already caught for Vitals and Diagnosis, I'll make sure any are also caught in Data and Processing.

**Comment by ss842** [comment]
left in the air:
-read the docs
-pep8
