### ISSUE TITLE
Error Between Travis CI / Py.test and console -- Class Composition branch

### ISSUE THREAD

**Issue by jhoballah** [yashasaxena/bme590hrm#76]
So we're having a strange issue in our Travis CI / py.test outputs in our ClassComposition branch.

Our unit tests are now failing for test_avghr_withfraction(), test_avghr_with_float_as_string(), and test_avghr_with_float(), and giving us an average HR of 12 instead of 84. 

However, when we basically code out our unit tests line by line in iPython, it's giving us the correct average HR value of 84. Why would this be happening?

**Comment by mlp6** [comment]
Are you using an identical input when you do it interactively?

**Comment by jhoballah** [comment]
Exactly identical. That’s why we’re confused :(

**Comment by ss842** [comment]
@yashasaxena and I figured out the problem, we'll update you later, thanks @mlp6
